A couple small code cleanups to address errors in the fabmo log (#945)
* Lift up the default 'update' implementation from DashboardConfig to Config.

Because the fallback case of no G2 board connected ends up with a
'Config' object instead of a 'G2Config', it blows up due to
Config.update not existing.

The logged error message was:

debug: ==> call Set Many with:   [config]
UNCAUGHT EXCEPTION
TypeError: this.update is not a function
    at Config.setMany (/fabmo/config/config.js:79:7)
    at post_config (/fabmo/routes/config.js:113:19)
    at nextTick (/fabmo/node_modules/restify/lib/chain.js:167:13)
    at processTicksAndRejections (node:internal/process/task_queues:78:11)
info: Saving log... [log]

* since DashboardConfig inherits from Config, we don't the copy of the
now-default Update method

* Better protect executeRuntimeCode against not having a runtime defined.

Previously, trying to run this method with no G2 connection resulted in:

error: TypeError: Cannot read properties of undefined (reading 'needsAuth')
    at Machine.executeRuntimeCode (/fabmo/machine.js:1093:26)
    at Socket.<anonymous> (/fabmo/routes/websocket.js:148:13)
    at Socket.emit (node:events:527:28)
    at Socket.emitUntyped (/fabmo/node_modules/socket.io/dist/typed-events.js:69:22)
    at /fabmo/node_modules/socket.io/dist/socket.js:465:39
    at processTicksAndRejections (node:internal/process/task_queues:78:11) [websocket]

Now it results in:

debug: Rejecting attempt to execute runtime code with no defined runtime.
debug: { cmd: 'enter' }

Co-authored-by: kyle-kingsbury <kyle.kingsbury@shopbottools.com>