Lift up the default 'update' implementation from DashboardConfig to Config.
Because the fallback case of no G2 board connected ends up with a
'Config' object instead of a 'G2Config', it blows up due to
Config.update not existing.

The logged error message was:

debug: ==> call Set Many with:   [config]
UNCAUGHT EXCEPTION
TypeError: this.update is not a function
    at Config.setMany (/fabmo/config/config.js:79:7)
    at post_config (/fabmo/routes/config.js:113:19)
    at nextTick (/fabmo/node_modules/restify/lib/chain.js:167:13)
    at processTicksAndRejections (node:internal/process/task_queues:78:11)
info: Saving log... [log]